name: Convert Video to YouTube Ready

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'ضع رابط الفيديو هنا'
        required: true
        type: string

jobs:
  fix_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg & Curl
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

      - name: Download and Re-encode Video
        run: |
          URL="${{ github.event.inputs.video_url }}"
          
          # تحميل الملف
          curl -L "$URL" -o input.tmp
          
          # معالجة الفيديو للحجم المناسب والجودة الممتازة بدون شاشة سوداء
          ffmpeg -i input.tmp -c:v libx264 -pix_fmt yuv420p -crf 23 -preset medium -c:a aac -b:a 128k -movflags +faststart "output_ready.mp4"

      - name: Upload Processed Video
        uses: actions/upload-artifact@v4
        with:
          name: converted_episode
          path: output_ready.mp4
