name: Download IPTV M3U

on:
  workflow_dispatch: # يتيح لك تشغيله يدوياً بضغطة زر

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch M3U File
        run: |
          curl -A "VLC/3.0.16 LibVLC/3.0.16" -L "http://univ-new.top:2095/get.php?username=Ddt00000&password=00000000&type=m3u&output=ts" -o playstop.m3u

      - name: Upload M3U as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-playlist
          path: playstop.m3u
